// SPDX-License-Identifier: MPL-2.0

// Package tlatrace writes traces recorded from real code as a generated TLA+
// module, for trace validation by `scripts/formal.py traces`.
//
// A harness records one Record per observation: a projection of the model's
// variables, as TLA+ literals. Accepted traces come from running the real
// code; Rejected traces are targeted mutations that trace validation must
// refuse, proving the check is not vacuous.
package tlatrace

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"testing"
)

// EnvDir names the directory harnesses write to. Harnesses skip when unset.
const EnvDir = "INVOWK_FORMAL_TRACE_DIR"

type (
	// Record maps a projected variable name to its TLA+ literal.
	Record map[string]string

	// Traces are the traces one harness produced.
	Traces struct {
		Accepted [][]Record
		Rejected [][]Record
	}
)

// Str renders a TLA+ string literal.
func Str(s string) string { return strconv.Quote(s) }

// Bool renders a TLA+ boolean.
func Bool(b bool) string {
	if b {
		return "TRUE"
	}
	return "FALSE"
}

// Set renders a TLA+ set of string literals.
func Set(elems ...string) string {
	quoted := make([]string, 0, len(elems))
	for _, e := range elems {
		quoted = append(quoted, Str(e))
	}
	slices.Sort(quoted)
	return "{" + strings.Join(quoted, ", ") + "}"
}

// Dir returns the output directory, skipping the test when trace output is off.
func Dir(t *testing.T) string {
	t.Helper()
	dir := os.Getenv(EnvDir)
	if dir == "" {
		t.Skipf("trace harness: set %s to record traces", EnvDir)
	}
	return dir
}

func renderRecord(r Record) string {
	keys := make([]string, 0, len(r))
	for k := range r {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	fields := make([]string, 0, len(keys))
	for _, k := range keys {
		fields = append(fields, fmt.Sprintf("%s |-> %s", k, r[k]))
	}
	return "[" + strings.Join(fields, ", ") + "]"
}

func renderTraces(traces [][]Record) string {
	rendered := make([]string, 0, len(traces))
	for _, trace := range traces {
		records := make([]string, 0, len(trace))
		for _, r := range trace {
			records = append(records, renderRecord(r))
		}
		rendered = append(rendered, "<<"+strings.Join(records, ", ")+">>")
	}
	return "<<" + strings.Join(rendered, ",\n    ") + ">>"
}

// Write emits <module>.tla defining Accepted and Rejected, and <module>.json
// with their counts for the runner.
func Write(t *testing.T, dir, module string, traces Traces) {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("create trace dir: %v", err)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "---- MODULE %s ----\n\\* Generated by a trace harness; do not edit.\n", module)
	fmt.Fprintf(&b, "Accepted == %s\n\n", renderTraces(traces.Accepted))
	fmt.Fprintf(&b, "Rejected == %s\n====\n", renderTraces(traces.Rejected))
	if err := os.WriteFile(filepath.Join(dir, module+".tla"), []byte(b.String()), 0o644); err != nil {
		t.Fatalf("write trace module: %v", err)
	}
	counts, err := json.Marshal(map[string]int{"accepted": len(traces.Accepted), "rejected": len(traces.Rejected)})
	if err != nil {
		t.Fatalf("encode trace counts: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, module+".json"), counts, 0o644); err != nil {
		t.Fatalf("write trace counts: %v", err)
	}
}
