commit_attribution = "Codex <noreply@openai.com>"
model_context_window = 1000000
model_auto_compact_token_limit = 900000

[features]
multi_agent = true
memories = true
codex_git_commit = true
default_mode_request_user_input = true
