version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - govet
    - ineffassign
    - nakedret
    - nilerr
    - revive
    - staticcheck
    - unused
    - wrapcheck
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam # TUI options are intentionally passed by value
    gosec:
      excludes:
        - G104 # Unhandled errors - covered by errcheck linter
        - G115 # Integer overflow - many false positives in Go
        - G204 # Subprocess with variable - command runner by design
        - G301 # Dir perms > 0750 - directories need 0755 for traversability
        - G302 # File created with excessive perms - config files need world-readable
        - G304 # File inclusion via variable - must read user config/invkfiles
        - G306 # WriteFile perms > 0600 - config/pack files need 0644 for readability
      config:
        global:
          tests: false
    govet:
      enable:
        - shadow
    nakedret:
      max-func-lines: 10
    revive:
      rules:
        - name: exported
          severity: warning
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Join(
        # Standard library signatures - context usually clear from call site
        - .Close()
        - .Read(
        - .Write(
        - .WriteString(
        - .Run()
        - .Start()
        - .Wait()
        - .Open()
        - .Info()
        - .Shutdown(
        - .CombinedOutput()
        - io.Copy(
        - io.ReadAll(
        - os.MkdirAll(
        - os.Open(
        - os.OpenFile(
        - os.Create(
        - os.CreateTemp(
        - os.ReadFile(
        - os.ReadDir(
        - os.WriteFile(
        - os.Stat(
        - filepath.Walk(
        - exec.LookPath(
        - json.Unmarshal(
        - json.Marshal(
      ignore-package-globs:
        - invowk-cli/*  # Internal module packages - wrapped at public API boundaries
        - github.com/charmbracelet/*  # TUI library - errors self-descriptive
        - github.com/go-git/*  # Git library - errors already descriptive
        - github.com/creack/pty  # PTY library - used in context
        - golang.org/x/sys/*  # Syscall wrappers - low-level
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
