version: "2"
run:
  modules-download-mode: readonly
  tests: true
  go: ""
linters:
  default: standard
  enable:
    - modernize
    - goconst
    # CRITICAL: decorder and funcorder MUST BE KEPT enabled.
    # These linters enforce consistent declaration ordering (const/var/type/func)
    # and function ordering (exported before unexported) across the codebase.
    # Do NOT disable or remove these linters.
    - decorder
    - funcorder
    - copyloopvar
    - iotamixing
    - mirror
    - gochecksumtype
    - zerologlint
    - asasalint
    - asciicheck
    - bidichk
    - durationcheck
    - errname
    - nilerr
    - nilnil
    - noctx
    - predeclared
    - reassign
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - gocritic
    - bodyclose
    - errcheck
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - govet
    - ineffassign
    - nakedret
    - revive
    - staticcheck
    - unused
    - wrapcheck
  settings:
    decorder:
      # Required order of `type`, `const`, `var` and `func` declarations inside a file.
      # Default: types before constants before variables before functions.
      dec-order:
        - const
        - var
        - type
        - func
      # If true, underscore vars (vars with "_" as the name) will be ignored at all checks.
      # Default: false (underscore vars are not ignored)
      ignore-underscore-vars: false
      # If true, order of declarations is not checked at all.
      # Default: true (disabled)
      disable-dec-order-check: false
      # If true, `init` func can be anywhere in file (does not have to be declared before all other functions).
      # Default: true (disabled)
      disable-init-func-first-check: false
      # If true, multiple global `type`, `const` and `var` declarations are allowed.
      # Default: true (disabled)
      disable-dec-num-check: false
      # If true, type declarations will be ignored for dec num check.
      # Default: false (type statements are not ignored)
      disable-type-dec-num-check: false
      # If true, const declarations will be ignored for dec num check.
      # Default: false (const statements are not ignored)
      disable-const-dec-num-check: false
      # If true, var declarations will be ignored for dec num check.
      # Default: false (var statements are not ignored)
      disable-var-dec-num-check: false
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam # TUI options are intentionally passed by value
    errcheck:
      # Report `a := b.(MyStruct)` when `a, ok := ...` should be.
      # Disabled: Many type assertions are in bubbletea TUI code where types are guaranteed by the framework
      check-type-assertions: false # Default: false

      # Report skipped checks:`num, _ := strconv.Atoi(numStr)`.
      check-blank: true # Default: false

      # Function to skip.
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        # CLI flag getters - errors only occur for undefined flags, which are caught at compile time
        - (*github.com/spf13/pflag.FlagSet).GetString
        - (*github.com/spf13/pflag.FlagSet).GetStringArray
        - (*github.com/spf13/pflag.FlagSet).GetStringSlice
        - (*github.com/spf13/pflag.FlagSet).GetBool
        - (*github.com/spf13/pflag.FlagSet).GetInt
        - (*github.com/spf13/pflag.FlagSet).GetInt64
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        # Output functions - errors writing to stdout/stderr are not actionable
        - fmt.Fprintln
        - fmt.Fprintf
        - fmt.Fprint
        - fmt.Println
        - fmt.Printf
        - fmt.Print
        # Sscanf - parse errors fall back to zero values by design
        - fmt.Sscanf
        - fmt.Sscan
        # File close in defer - named return pattern recommended but explicit ignores are acceptable
        - (*os.File).Close
        - (*compress/gzip.Reader).Close
        - (*compress/gzip.Writer).Close
        - (*archive/zip.ReadCloser).Close
        # Server shutdown - errors during stop are not recoverable
        - (*invowk-cli/internal/sshserver.Server).Stop
        - (*invowk-cli/internal/tuiserver.Server).Stop
        # Temp file cleanup - best-effort, failures are logged but not critical
        - os.Remove
        - os.RemoveAll
        # Test utilities - errors in test setup are caught by test failures
        - os.Chdir
        - os.Setenv
        - os.Unsetenv
        - os.Getwd
        - os.UserHomeDir
        - io.Copy(os.Stdout)
        # Path operations - errors are handled by subsequent operations that use the path
        - path/filepath.Rel
        - path/filepath.Abs
        # Archive operations in tests - setup errors are caught by test failures
        - (*archive/zip.Writer).Create
        - (*archive/zip.Writer).Close
        - (io.Writer).Write
        # HTTP/network close - best-effort cleanup
        - (*net/http.Response).Body.Close
        - (net.Conn).Close
        - (io.Closer).Close
        - (net.Listener).Close
        - (*net/http.Server).Close
        # HTTP request creation - setup errors caught by subsequent operations
        - http.NewRequestWithContext
        # JSON encoding/marshal - errors in response writing are not recoverable
        - json.Marshal
        - (*encoding/json.Encoder).Encode
        # HTTP response writing - errors are not recoverable, connection is already gone
        - (net/http.ResponseWriter).Write
        # UI rendering - errors during rendering are not actionable
        - (*invowk-cli/internal/issue.Issue).Render
        # Stdin stat - checking if stdin is a terminal, error just means no
        - (*os.File).Stat
        # exec.LookPath - error means binary not found, handled by empty path
        - os/exec.LookPath
        # os.Chmod - permission errors are best-effort
        - os.Chmod
        # os.Executable - getting current executable, fallback handled
        - os.Executable
        # os.ReadDir - directory listing errors are handled by empty list
        - os.ReadDir
        # syscall.Syscall - low-level syscall, errors handled in return value
        - syscall.Syscall
        # SSH session exit - errors during exit are not recoverable
        - (*golang.org/x/crypto/ssh.Session).Exit
        # filepath.Walk - walker error handling is in callback
        - path/filepath.Walk
        # Image exists check - error handled by false return
        - (*invowk-cli/internal/container.Engine).ImageExists
    gosec:
      excludes:
        - G104 # Unhandled errors - covered by errcheck linter
        - G115 # Integer overflow - many false positives in Go
        - G204 # Subprocess with variable - command runner by design
        - G301 # Dir perms > 0750 - directories need 0755 for traversability
        - G302 # File created with excessive perms - config files need world-readable
        - G304 # File inclusion via variable - must read user config/invkfiles
        - G306 # WriteFile perms > 0600 - config/module files need 0644 for readability
      config:
        global:
          tests: false
    govet:
      enable:
        - shadow
    nakedret:
      max-func-lines: 10
    revive:
      rules:
        - name: exported
          severity: warning
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Join(
        # Standard library signatures - context usually clear from call site
        - .Close()
        - .Read(
        - .Write(
        - .WriteString(
        - .Run()
        - .Start()
        - .Wait()
        - .Open()
        - .Info()
        - .Shutdown(
        - .CombinedOutput()
        - io.Copy(
        - io.ReadAll(
        - os.MkdirAll(
        - os.Open(
        - os.OpenFile(
        - os.Create(
        - os.CreateTemp(
        - os.ReadFile(
        - os.ReadDir(
        - os.WriteFile(
        - os.Stat(
        - filepath.Walk(
        - exec.LookPath(
        - json.Unmarshal(
        - json.Marshal(
      ignore-package-globs:
        - invowk-cli/*  # Internal module packages - wrapped at public API boundaries
        - github.com/charmbracelet/*  # TUI library - errors self-descriptive
        - github.com/go-git/*  # Git library - errors already descriptive
        - github.com/creack/pty  # PTY library - used in context
        - golang.org/x/sys/*  # Syscall wrappers - low-level
    tagliatelle:
      # Config and protocol files intentionally use snake_case for JSON tags
      # to match CUE/YAML conventions and maintain backward compatibility
      case:
        rules:
          json: snake
    thelper:
      # Allow test closures (table-driven tests) without t.Helper() requirement
      # Only check actual helper functions for t.Helper() call
      test:
        first: false  # Don't require t.Helper() to be first statement
        name: false   # Don't require parameter to be named t
        begin: true   # Do require t.Helper() at the beginning of helpers
      benchmark:
        first: false
        name: false
        begin: true
      tb:
        first: false
        name: false
        begin: true
      fuzz:
        first: false
        name: false
        begin: true
    mnd:
      # Ignore common patterns that are well-understood
      ignored-numbers:
        - "2"     # Common for version parsing (major.minor)
        - "3"     # Common for version parsing (major.minor.patch)
        - "4"     # Common for IPv4 octets, padding, quad structures
        - "5"     # Common for timeouts (5 minutes), short intervals
        - "6"     # Hex color length
        - "8"     # Byte/octet counts
        - "10"    # Base 10 for number parsing
        - "12"    # Common for short hashes, git short commits
        - "16"    # Base 16 for hex parsing, common buffer sizes
        - "20"    # Minimum widths for UI components
        - "32"    # ASCII control char limit, common buffer/hash sizes
        - "50"    # Common UI widths
        - "64"    # Common for int64 bit size
        - "90"    # Common UI widths for tables
        - "100"   # Percentages
        - "255"   # Max byte value
        - "512"   # Common path/name length limits
        - "4096"  # Common buffer/path length limits
        - "65535" # Max uint16 (port numbers)
      ignored-files:
        - "_test.go"  # Tests often have magic numbers for test data
      ignored-functions:
        - "os.MkdirAll"     # File permissions are self-documenting
        - "time.NewTicker"  # Time durations are self-documenting
        - "min"             # UI dimension calculations
        - "max"             # UI dimension calculations
        - "os.OpenFile"    # File permissions are self-documenting
        - "os.WriteFile"   # File permissions are self-documenting
        - "os.Chmod"       # File permissions are self-documenting
        - "os.Mkdir"       # File permissions are self-documenting
        - "make"           # Capacity hints are often magic numbers
        - "strings.SplitN" # Split count is often 2 or 3
      checks:
        - argument
        - case
        - condition
        - return
    goconst:
      # Require more occurrences before suggesting constant
      min-occurrences: 5
      # Minimum string length to trigger the linter (ignore short strings like "true", "env")
      min-len: 6
      # Ignore test files which often have repeated test data
      ignore-tests: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      # Don't enforce errcheck in test files - test setup/cleanup errors are caught by test failures
      - linters:
          - errcheck
        path: _test\.go$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # No, no skips, everything should be reported.
  uniq-by-line: false
formatters:
  enable:
    # Might not be that important but I prefer to keep all of them.
    # `gofumpt` is amazing, kudos to Daniel Marti https://github.com/mvdan/gofumpt
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
