# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser configuration for invowk
# Documentation: https://goreleaser.com

version: 2

project_name: invowk

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: invowk
    binary: invowk
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'invowk-cli/cmd/invowk.Version={{.Version}}'
      - -X 'invowk-cli/cmd/invowk.Commit={{.ShortCommit}}'
      - -X 'invowk-cli/cmd/invowk.BuildDate={{.Date}}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    ignore:
      # Windows arm64 not commonly needed
      - goos: windows
        goarch: arm64
    hooks:
      post:
        # UPX compression for smaller binaries
        # Skip on macOS arm64 (UPX doesn't support it well)
        # Skip on Windows (UPX can cause antivirus false positives)
        - cmd: bash -c '{{ if eq .Os "windows" }}echo "Skipping UPX for Windows"{{ else if and (eq .Os "darwin") (eq .Arch "arm64") }}echo "Skipping UPX for macOS arm64"{{ else }}upx --best --lzma "{{ .Path }}"{{ end }}'
          output: true

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Use zip for Windows
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Cosign keyless signing using GitHub OIDC
signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: Performance
      regexp: '^perf(\(.+\))?:'
      order: 2
    - title: Refactoring
      regexp: '^refactor(\(.+\))?:'
      order: 3
    - title: Other
      order: 999

release:
  github:
    owner: invowk
    name: invowk
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## invowk {{ .Version }}

    A dynamically extensible command runner.
  footer: |
    ---
    {{ if .PreviousTag }}
    **Full Changelog**: https://github.com/invowk/invowk/compare/{{ .PreviousTag }}...{{ .Tag }}
    {{ else }}
    **Full Changelog**: https://github.com/invowk/invowk/commits/{{ .Tag }}
    {{ end }}
    ### Verify Signatures

    All release artifacts are signed with [Cosign](https://github.com/sigstore/cosign) using keyless signing.

    ```bash
    # Download the checksum file and signature
    cosign verify-blob \
      --certificate checksums.txt.pem \
      --signature checksums.txt.sig \
      --certificate-identity-regexp='https://github\.com/invowk/invowk/.*' \
      --certificate-oidc-issuer='https://token.actions.githubusercontent.com' \
      checksums.txt
    ```

# Homebrew tap (disabled for now - uncomment to enable)
# brews:
#   - name: invowk
#     repository:
#       owner: invowk
#       name: homebrew-tap
#       token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
#     homepage: https://invowk.dev
#     description: A dynamically extensible command runner
#     license: MPL-2.0
#     install: |
#       bin.install "invowk"
#     test: |
#       system "#{bin}/invowk", "--version"

# Winget (disabled for now - uncomment to enable)
# winget:
#   - name: invowk
#     publisher: invowk
#     short_description: A dynamically extensible command runner
#     license: MPL-2.0
#     homepage: https://invowk.dev
#     repository:
#       owner: invowk
#       name: winget-pkgs
#       token: "{{ .Env.WINGET_TOKEN }}"
