# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser configuration for invowk
# Documentation: https://goreleaser.com

version: 2

project_name: invowk

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: invowk
    binary: invowk
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'github.com/invowk/invowk/cmd/invowk.Version={{.Version}}'
      - -X 'github.com/invowk/invowk/cmd/invowk.Commit={{.ShortCommit}}'
      - -X 'github.com/invowk/invowk/cmd/invowk.BuildDate={{.Date}}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    ignore:
      # Windows arm64 not commonly needed
      - goos: windows
        goarch: arm64
    hooks:
      post:
        # UPX compression for smaller binaries
        # Skip on macOS (UPX-compressed Mach-O binaries trigger Gatekeeper issues and break notarization)
        # Skip on Windows (UPX can cause antivirus false positives)
        - cmd: bash -c '{{ if eq .Os "windows" }}echo "Skipping UPX for Windows"{{ else if eq .Os "darwin" }}echo "Skipping UPX for macOS"{{ else }}upx --best --lzma "{{ .Path }}"{{ end }}'
          output: true

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Use zip for Windows
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Cosign keyless signing using GitHub OIDC
signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

changelog:
  use: github-native

release:
  github:
    owner: invowk
    name: invowk
  draft: false
  prerelease: auto
  # Prereleases must not be marked as "latest" — GitHub API rejects
  # PATCH requests that set both prerelease=true and make_latest=true.
  make_latest: "{{ if .Prerelease }}false{{ else }}true{{ end }}"
  mode: replace
  header: |
    ## invowk {{ .Version }}
  footer: |
    ---
    {{ if .PreviousTag }}
    **Full Changelog**: https://github.com/invowk/invowk/compare/{{ .PreviousTag }}...{{ .Tag }}
    {{ else }}
    **Full Changelog**: https://github.com/invowk/invowk/commits/{{ .Tag }}
    {{ end }}
    ### Verify Signatures

    All release artifacts are signed with [Cosign](https://github.com/sigstore/cosign) using keyless signing.

    ```bash
    # Download the checksum file and signature
    cosign verify-blob \
      --certificate checksums.txt.pem \
      --signature checksums.txt.sig \
      --certificate-identity-regexp='https://github\.com/invowk/invowk/.*' \
      --certificate-oidc-issuer='https://token.actions.githubusercontent.com' \
      checksums.txt
    ```

# Homebrew cask — auto-pushes cask to invowk/homebrew-tap on stable releases.
# Requires HOMEBREW_TAP_TOKEN secret (fine-grained PAT with contents:write on the tap repo).
# Migrated from brews → homebrew_casks (GoReleaser v2.10+); Casks are the conventional
# Homebrew mechanism for distributing pre-compiled binaries.
homebrew_casks:
  - name: invowk
    repository:
      owner: invowk
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    # skip_upload: auto skips cask push for snapshot builds and pre-releases.
    # Only stable releases (non-draft, non-prerelease) update the tap.
    skip_upload: auto
    homepage: https://invowk.dev
    description: A dynamically extensible command runner
    license: MPL-2.0
    binaries:
      - invowk
    # Remove macOS quarantine attribute — invowk binaries are not signed/notarized.
    # xattr -dr is idempotent (exits 0 when attribute absent).
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/invowk"]
          end
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"

# WinGet — auto-generates manifests and opens PRs to microsoft/winget-pkgs on stable releases.
# Requires WINGET_TOKEN secret (classic PAT with public_repo scope for cross-repo fork PRs).
# First version must be submitted manually; automation handles subsequent updates.
winget:
  - name: invowk
    publisher: invowk
    publisher_url: https://invowk.dev
    publisher_support_url: https://github.com/invowk/invowk/issues
    package_identifier: Invowk.Invowk
    license: MPL-2.0
    license_url: https://github.com/invowk/invowk/blob/HEAD/LICENSE
    copyright: Copyright invowk contributors
    homepage: https://invowk.dev
    short_description: A dynamically extensible command runner
    description: |-
      Invowk is a dynamically extensible command runner supporting multiple execution
      runtimes: native shell, virtual shell, and containerized execution (Docker/Podman).
    tags:
      - cli
      - command-runner
      - devops
      - task-runner
    release_notes_url: "https://github.com/invowk/invowk/releases/tag/{{ .Tag }}"
    installation_notes: "Restart your terminal session for the 'invowk' command to become available on PATH."
    goamd64: v3
    skip_upload: auto
    repository:
      owner: invowk
      name: winget-pkgs
      branch: "invowk-{{ .Version }}"
      token: "{{ .Env.WINGET_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
    commit_msg_template: "New version: Invowk.Invowk version {{ .Version }}"
