// SPDX-License-Identifier: MPL-2.0

package moduleops

import (
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/invowk/invowk/internal/app/modulecache"
	"github.com/invowk/invowk/internal/provision"
	"github.com/invowk/invowk/internal/testutil/alloygolden"
	"github.com/invowk/invowk/internal/testutil/fstree"
	"github.com/invowk/invowk/internal/testutil/mpctree"
	"github.com/invowk/invowk/pkg/invowkfile"
	"github.com/invowk/invowk/pkg/invowkmod"
	"github.com/invowk/invowk/pkg/types"
)

// modulePathContainmentGoldenFile holds every instance of
// formal/alloy/ModulePathContainment.als's `golden` command, regenerated by
// `scripts/formal.py golden ModulePathContainment`.
const modulePathContainmentGoldenFile = "testdata/formal/module_path_containment_golden.json.gz"

// TestModulePathContainment_GoldenVectors replays every operation in design D5.2
// against the real functions on a materialised filesystem: for each instance it
// materialises the tree with fstree, compares the per-layer decisions the model
// recorded (validate, lexical containment, physical containment, accept, touched
// node) with the real behaviour, and asserts the Go transcriptions of the
// discovery facts and policy on every instance. Instances that need an
// unavailable capability are skipped and counted per capability.
func TestModulePathContainment_GoldenVectors(t *testing.T) {
	t.Parallel()

	instances := alloygolden.Load(t, modulePathContainmentGoldenFile, "ModulePathContainment")
	cache := fstree.NewCache(t)
	scratch := t.TempDir() // reused copy destination, emptied after each tree
	admitted := map[string]bool{}
	report := mpctree.NewReporter(t)

	for i, inst := range instances {
		c := mpctree.FromInstance(inst)
		key := c.StructuralKey()
		b := cache.Get(t, key, c.Spec)
		if b == nil {
			continue
		}
		if _, seen := admitted[key]; !seen {
			// Discovery admission (IsModule + Load), computed once per tree.
			mp := types.FilesystemPath(b.Path[c.OwnerAtom])
			_, loadErr := invowkmod.Load(mp)
			admitted[key] = invowkmod.IsModule(mp) && loadErr == nil
			assertDiscoveryFacts(report, i, c, b, admitted[key])
			assertCopyHashNoEscape(report, i, c, b, scratch)
		}
		replayInstance(report, i, c, b, admitted[key])
	}
	cache.LogSkips(t)
	report.Finish("ModulePathContainment", len(instances))
}

// replayInstance compares the per-layer decisions for one operation.
func replayInstance(report *mpctree.Reporter, i int, c mpctree.Case, b *fstree.Built, admit bool) {
	moduleRoot := b.Path[c.OwnerAtom]
	pathStr := c.RelPath(b)

	// Validate layer: the value type's syntactic check, per operation kind.
	gotValidate := realValidate(c.OpKind, pathStr)
	if gotValidate != c.Validates {
		report.Errorf("instance %d %s: real validate=%v, model=%v (path %q)", i, c.OpKind, gotValidate, c.Validates, pathStr)
	}

	// Physical containment (real EvalSymlinks against the materialised tree).
	gotPhys := physInside(moduleRoot, pathStr)
	if gotPhys != c.PhysInside {
		report.Errorf("instance %d %s: real physContains=%v, model=%v (path %q)", i, c.OpKind, gotPhys, c.PhysInside, pathStr)
	}

	// Accept + touch, bound end to end for script reads through the real
	// resolver; the interpreter re-opens the same path (SelectedScriptFilePath).
	if c.OpKind == mpctree.ScriptRead {
		accepts, touchReal := realScriptRead(moduleRoot, pathStr)
		effAccept := admit && accepts
		if effAccept != c.Accepts {
			report.Errorf("instance %d ScriptRead: real accept=%v, model=%v (path %q)", i, effAccept, c.Accepts, pathStr)
		}
		if effAccept {
			wantTouch := b.Path[c.TouchAtom]
			if !sameOrBothMissing(touchReal, wantTouch) {
				report.Errorf("instance %d ScriptRead: touched %q, model atom %q -> %q", i, touchReal, c.TouchAtom, wantTouch)
			}
		}
	}
}

// realValidate runs the real value-type validator for the operation kind.
func realValidate(kind mpctree.OpKind, pathStr string) bool {
	switch kind {
	case mpctree.ScriptRead:
		return invowkfile.ScriptFilePath(pathStr).Validate() == nil
	case mpctree.EnvRead:
		return invowkfile.ValidateEnvFilePath(pathStr) == nil
	case mpctree.ContainerfileRef:
		return invowkfile.ValidateContainerfilePath(pathStr, "") == nil
	case mpctree.WorkdirCwd, mpctree.VendorCopy, mpctree.Hash, mpctree.Unpack:
		// copy, hash, unpack, workdir have no value-type validate layer; the
		// model transcribes it as refShape = RelInside (no `..`, not absolute)
		return !filepath.IsAbs(pathStr) && !slices.Contains(strings.Split(pathStr, "/"), "..")
	}
	return false
}

// physInside reports whether the reference resolves physically inside the module
// root, using real filepath.EvalSymlinks (the policy's physical resolution).
func physInside(moduleRoot, pathStr string) bool {
	full := pathStr
	if !filepath.IsAbs(full) {
		full = filepath.Join(moduleRoot, filepath.FromSlash(pathStr))
	}
	resolved, err := filepath.EvalSymlinks(full)
	if err != nil {
		return false // dangling / cyclic: physical resolution undefined
	}
	return fstree.Within(moduleRoot, resolved) // moduleRoot is already a resolved real path
}

// realScriptRead invokes the real script resolver with a recording reader and
// returns whether the read was reached (accept) and the physical file opened.
func realScriptRead(moduleRoot, pathStr string) (accept bool, touched string) {
	sfp := invowkfile.ScriptFilePath(pathStr)
	impl := invowkfile.Implementation{Script: invowkfile.ImplementationScript{File: &sfp}}
	reader := func(p string) ([]byte, error) {
		accept = true
		// The touched node is the path's physical resolution, whether or not the
		// read then succeeds (a link to a directory resolves but ReadFile errors
		// with EISDIR; a dangling link fails to resolve and touches nothing).
		if resolved, rerr := filepath.EvalSymlinks(p); rerr == nil {
			touched = resolved
		}
		return os.ReadFile(p)
	}
	_, _ = impl.ResolveScriptWithFSAndModule("", invowkfile.FilesystemPath(moduleRoot), reader)
	return accept, touched
}

func sameOrBothMissing(gotResolved, wantAtomPath string) bool {
	if gotResolved == "" || wantAtomPath == "" {
		return gotResolved == "" && wantAtomPath == ""
	}
	gi, err1 := os.Stat(gotResolved)
	wi, err2 := os.Stat(wantAtomPath)
	if err1 != nil || err2 != nil {
		return false
	}
	return os.SameFile(gi, wi)
}

// assertDiscoveryFacts checks the Go transcription of the discovery facts on the
// materialised tree: an admitted module has no non-vendored inner symlink.
func assertDiscoveryFacts(report *mpctree.Reporter, i int, c mpctree.Case, b *fstree.Built, admit bool) {
	hasInner := false
	for _, n := range c.Spec.Nodes {
		if n.Kind != fstree.KindSymlink && n.Kind != fstree.KindJunction {
			continue
		}
		if underVendor(c, n) {
			continue
		}
		if fstree.Within(b.Path[c.OwnerAtom], b.Path[n.Atom]) {
			hasInner = true
		}
	}
	if hasInner && admit {
		report.Errorf("instance %d: module admitted despite a non-vendored inner symlink (loadScansNonLinkedRoot violated)", i)
	}
}

func underVendor(c mpctree.Case, n fstree.Node) bool {
	for cur := n; cur.Parent != ""; {
		parent := nodeByAtom(c, cur.Parent)
		if parent.Name == mpctree.VendoredModulesDir {
			return true
		}
		cur = parent
	}
	return false
}

func nodeByAtom(c mpctree.Case, atom string) fstree.Node {
	for _, n := range c.Spec.Nodes {
		if n.Atom == atom {
			return n
		}
	}
	return fstree.Node{}
}

// assertCopyHashNoEscape checks the real copy and hash never incorporate a node
// outside the module's physical root (copySkipsInnerLinks, hashSkipsLinks).
func assertCopyHashNoEscape(report *mpctree.Reporter, i int, c mpctree.Case, b *fstree.Built, scratch string) {
	src := b.Path[c.OwnerAtom]
	outside := outsideFileContents(c, b)
	defer func() { _ = os.RemoveAll(filepath.Join(scratch, "copy")) }()
	dst := filepath.Join(scratch, "copy", "modulecache")
	err := modulecache.CopyModuleDir(types.FilesystemPath(src), types.FilesystemPath(dst))
	if err == nil && copiedOutsideContent(dst, outside) {
		report.Errorf("instance %d: modulecache.CopyModuleDir copied content from outside the module", i)
	}
	assertCopyMatchesSource(report, i, "modulecache.CopyModuleDir", src, dst, err)
	dst = filepath.Join(scratch, "copy", "provision")
	err = provision.CopyDir(src, dst)
	if err == nil && copiedOutsideContent(dst, outside) {
		report.Errorf("instance %d: provision.CopyDir copied content from outside the module", i)
	}
	assertCopyMatchesSource(report, i, "provision.CopyDir", src, dst, err)
	if _, err := invowkmod.ComputeModuleHash(src); err != nil {
		report.Errorf("instance %d: ComputeModuleHash error: %v", i, err)
	}
}

// outsideFileContents collects the content tags of file nodes that lie outside
// the module's physical root; a correct copy never surfaces any of them.
func outsideFileContents(c mpctree.Case, b *fstree.Built) map[string]bool {
	moduleRoot := b.Path[c.OwnerAtom]
	out := map[string]bool{}
	for _, n := range c.Spec.Nodes {
		if n.Kind != fstree.KindFile {
			continue
		}
		if !fstree.Within(moduleRoot, b.Path[n.Atom]) {
			out[n.Content] = true
		}
	}
	return out
}

// copiedOutsideContent reports whether any regular file under dir carries the
// content of an outside node (which a symlink-following copy would leak).
func copiedOutsideContent(dir string, outside map[string]bool) bool {
	if len(outside) == 0 {
		return false
	}
	leaked := false
	_ = filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil //nolint:nilerr // best-effort scan
		}
		data, readErr := os.ReadFile(path) //nolint:gosec // G122: scans a test-owned copy destination
		if readErr == nil && outside[string(data)] {
			leaked = true
		}
		return nil
	})
	return leaked
}

// assertCopyMatchesSource checks a copy against an independent walk of its
// source (copySkipsInnerLinks): the source root is followed, inner symlinks are
// skipped, and every other directory and regular file arrives with its
// content. A source that does not resolve to a directory must fail the copy.
func assertCopyMatchesSource(report *mpctree.Reporter, i int, name, src, dst string, copyErr error) {
	want, wantErr := copiedTreeEntries(src)
	if wantErr != nil {
		if copyErr == nil {
			report.Errorf("instance %d: %s copied a source that does not resolve to a directory (%v)", i, name, wantErr)
		}
		return
	}
	if copyErr != nil {
		report.Errorf("instance %d: %s failed on a readable module: %v", i, name, copyErr)
		return
	}
	got, err := copiedTreeEntries(dst)
	if err != nil {
		report.Errorf("instance %d: %s destination unreadable: %v", i, name, err)
		return
	}
	if !maps.Equal(got, want) {
		report.Errorf("instance %d: %s copied %v, want %v", i, name, slices.Sorted(maps.Keys(got)), slices.Sorted(maps.Keys(want)))
	}
}

// copiedTreeEntries maps each directory ("rel/") and regular file (rel ->
// content) below root, after resolving root itself, without following inner
// symlinks.
func copiedTreeEntries(root string) (map[string]string, error) {
	resolved, err := filepath.EvalSymlinks(root)
	if err != nil {
		return nil, fmt.Errorf("resolve %s: %w", root, err)
	}
	info, err := os.Stat(resolved)
	if err != nil {
		return nil, err
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("%s is not a directory", root)
	}
	entries := map[string]string{}
	err = filepath.WalkDir(resolved, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, relErr := filepath.Rel(resolved, path)
		if relErr != nil {
			return fmt.Errorf("relative path of %s: %w", path, relErr)
		}
		switch {
		case d.Type()&os.ModeSymlink != 0:
		case d.IsDir():
			entries[filepath.ToSlash(rel)+"/"] = ""
		default:
			data, readErr := os.ReadFile(path) //nolint:gosec // G122: reads a test-owned materialised tree
			if readErr != nil {
				return readErr
			}
			entries[filepath.ToSlash(rel)] = string(data)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk %s: %w", root, err)
	}
	return entries, nil
}
