// AUTO-GENERATED by scripts/snapshot-version-assets.mjs — do not edit manually.
import type { Snippet } from '../snippets';
import v0_1_0 from './v0.1.0';
import v0_1_0_alpha_3 from './v0.1.0-alpha.3';
import v0_1_0_alpha_2 from './v0.1.0-alpha.2';
import v0_1_0_alpha_1 from './v0.1.0-alpha.1';

const versionMap: Record<string, Record<string, Snippet>> = {
  '0.1.0': v0_1_0,
  '0.1.0-alpha.3': v0_1_0_alpha_3,
  '0.1.0-alpha.2': v0_1_0_alpha_2,
  '0.1.0-alpha.1': v0_1_0_alpha_1,
};

export function resolveVersionSnippets(version: string): Record<string, Snippet> | undefined {
  return versionMap[version];
}
