// AUTO-GENERATED by scripts/snapshot-version-assets.mjs — do not edit manually.
import v0_5_0 from './v0.5.0';
import v0_4_0 from './v0.4.0';
import v0_3_0 from './v0.3.0';
import v0_2_0 from './v0.2.0';
import v0_1_0 from './v0.1.0';
import v0_1_0_alpha_3 from './v0.1.0-alpha.3';
import v0_1_0_alpha_2 from './v0.1.0-alpha.2';
import v0_1_0_alpha_1 from './v0.1.0-alpha.1';

const versionMap: Record<string, Record<string, string>> = {
  '0.5.0': v0_5_0,
  '0.4.0': v0_4_0,
  '0.3.0': v0_3_0,
  '0.2.0': v0_2_0,
  '0.1.0': v0_1_0,
  '0.1.0-alpha.3': v0_1_0_alpha_3,
  '0.1.0-alpha.2': v0_1_0_alpha_2,
  '0.1.0-alpha.1': v0_1_0_alpha_1,
};

export function resolveVersionDiagramPaths(version: string): Record<string, string> | undefined {
  return versionMap[version];
}
