// SPDX-License-Identifier: MPL-2.0

package invowkmod

import (
	"slices"
	"testing"

	"github.com/invowk/invowk/internal/testutil/alloygolden"
)

// dependencyClosureGoldenFile holds every instance of
// formal/alloy/DependencyClosure.als's `golden` command, regenerated by
// `scripts/formal.py golden DependencyClosure`.
const dependencyClosureGoldenFile = "testdata/formal/dependency_closure_golden.json.gz"

// closureGoldenCase is one DependencyClosure instance: root requirements, the
// requirements declared by each key's module, and the model's one-step
// diagnostic key set.
type closureGoldenCase struct {
	roots    []ModuleRef
	requires map[ModuleRefKey][]ModuleRef
	wantDiag []ModuleRefKey
}

func closureGoldenRef(keyAtom string) ModuleRef {
	return ModuleRef{GitURL: GitURL(alloygolden.GitURL(keyAtom)), Version: "^1.0.0"}
}

func closureGoldenCaseFrom(inst alloygolden.Instance) closureGoldenCase {
	root := inst.Atoms("Root")[0] // a one sig; alloygolden.Load checks the file
	c := closureGoldenCase{requires: make(map[ModuleRefKey][]ModuleRef)}
	for _, keyAtom := range inst.Targets("roots", root) {
		c.roots = append(c.roots, closureGoldenRef(keyAtom))
	}
	for _, modAtom := range inst.Atoms("Mod") {
		key := closureGoldenRef(inst.Target("key", modAtom)).Key()
		for _, reqAtom := range inst.Targets("requires", modAtom) {
			c.requires[key] = append(c.requires[key], closureGoldenRef(reqAtom))
		}
	}
	for _, keyAtom := range inst.Targets("diagSet", root) {
		c.wantDiag = append(c.wantDiag, closureGoldenRef(keyAtom).Key())
	}
	slices.Sort(c.wantDiag)
	return c
}

func diagnosticKeys(diags []MissingTransitiveDepDiagnostic) []ModuleRefKey {
	keys := make([]ModuleRefKey, 0, len(diags))
	for _, d := range diags {
		keys = append(keys, d.MissingRef.Key())
	}
	slices.Sort(keys)
	return keys
}

// TestDependencyClosureGoldenVectors replays every DependencyClosure instance
// against CheckMissingTransitiveDeps and CheckMissingVendoredTransitiveDeps:
// both must report exactly the model's one-step diagnostic key set, once per key.
func TestDependencyClosureGoldenVectors(t *testing.T) {
	t.Parallel()

	instances := alloygolden.Load(t, dependencyClosureGoldenFile, "DependencyClosure")
	disagreements := 0
	for i, inst := range instances {
		c := closureGoldenCaseFrom(inst)

		resolved := make([]*ResolvedModule, 0, len(c.roots))
		vendored := make([]*Module, 0, len(c.roots))
		rootReqs := make([]ModuleRequirement, 0, len(c.roots))
		for _, root := range c.roots {
			id := ModuleID(root.Key())
			resolved = append(resolved, &ResolvedModule{ModuleRef: root, ModuleID: id, TransitiveDeps: c.requires[root.Key()]})
			reqs := make([]ModuleRequirement, 0, len(c.requires[root.Key()]))
			for _, dep := range c.requires[root.Key()] {
				reqs = append(reqs, ModuleRequirement(dep))
			}
			vendored = append(vendored, &Module{Metadata: &Invowkmod{Module: id, Requires: reqs}})
			rootReqs = append(rootReqs, ModuleRequirement(root))
		}

		for name, got := range map[string][]ModuleRefKey{
			"CheckMissingTransitiveDeps":         diagnosticKeys(CheckMissingTransitiveDeps(c.roots, resolved)),
			"CheckMissingVendoredTransitiveDeps": diagnosticKeys(CheckMissingVendoredTransitiveDeps(rootReqs, vendored)),
		} {
			if !slices.Equal(got, c.wantDiag) {
				disagreements++
				if disagreements <= 5 {
					t.Errorf("instance %d: %s keys = %v, model diagKeys = %v", i, name, got, c.wantDiag)
				}
			}
		}
	}
	if disagreements > 0 {
		t.Fatalf("%d disagreements with DependencyClosure.diagKeys over %d instances", disagreements, len(instances))
	}
}
