// SPDX-License-Identifier: MPL-2.0

package invowkmod

import (
	"crypto/sha256"
	"fmt"
	"slices"
	"testing"

	"github.com/invowk/invowk/internal/testutil/alloygolden"
	"github.com/invowk/invowk/pkg/types"
)

// lockIdentityGoldenFile holds every instance of formal/alloy/LockIdentity.als's
// `golden` command, regenerated by `scripts/formal.py golden LockIdentity`.
const lockIdentityGoldenFile = "testdata/formal/lock_identity_golden.json.gz"

func lockGoldenModuleID(atom string) ModuleID { return ModuleID(alloygolden.ModuleID(atom)) }

func lockGoldenHash(atom string) ContentHash {
	return ContentHash(fmt.Sprintf("sha256:%x", sha256.Sum256([]byte(atom))))
}

// lockFromAlloy builds a lock file whose entries carry the instance's module_id,
// namespace identity, and content hash. An entry without a namespace identity
// gets namespace "@1.0.0", whose prefix before "@" is empty.
func lockFromAlloy(inst alloygolden.Instance) *LockFile {
	lockAtom := inst.Atoms("Lock")[0]
	version := LockFileVersionV1
	if inst.In("V2", inst.Target("version", lockAtom)) {
		version = LockFileVersionV2
	}
	lock := &LockFile{Version: version, Modules: make(map[ModuleRefKey]LockedModule)}
	for _, entryAtom := range inst.Atoms("Entry") {
		entry := LockedModule{Namespace: "@1.0.0"}
		if mid := inst.Target("mid", entryAtom); mid != "" {
			entry.ModuleID = lockGoldenModuleID(mid)
		}
		if ns := inst.Target("nsId", entryAtom); ns != "" {
			entry.Namespace = ModuleNamespace(string(lockGoldenModuleID(ns)) + "@1.0.0")
		}
		if hash := inst.Target("hash", entryAtom); hash != "" {
			entry.ContentHash = lockGoldenHash(hash)
		}
		lock.Modules[ModuleRefKey(alloygolden.GitURL(entryAtom))] = entry
	}
	return lock
}

// TestLockIdentityGoldenVectors replays every LockIdentity instance against
// FindAmbiguousLockedModuleEntries and EvaluateVendoredModuleHash: both must
// agree with the model on which identities are ambiguous, missing, without a
// hash, or compared against exactly one locked hash.
func TestLockIdentityGoldenVectors(t *testing.T) {
	t.Parallel()

	instances := alloygolden.Load(t, lockIdentityGoldenFile, "LockIdentity")
	moduleDir := types.FilesystemPath(t.TempDir())
	statusSet := map[VendoredHashStatus]string{
		VendoredHashMissing:     "missing",
		VendoredHashAmbiguous:   "ambiguous",
		VendoredHashUnavailable: "unhashed",
		VendoredHashMismatch:    "compared",
		VendoredHashMatched:     "compared",
	}

	for i, inst := range instances {
		lock := lockFromAlloy(inst)
		lockAtom := inst.Atoms("Lock")[0]

		var gotAmbiguous []ModuleID
		for _, amb := range FindAmbiguousLockedModuleEntries(lock) {
			gotAmbiguous = append(gotAmbiguous, amb.ModuleID)
		}
		var wantAmbiguous []ModuleID
		for _, id := range inst.Targets("ambiguous", lockAtom) {
			wantAmbiguous = append(wantAmbiguous, lockGoldenModuleID(id))
		}
		slices.Sort(wantAmbiguous)
		if !slices.Equal(gotAmbiguous, wantAmbiguous) {
			t.Fatalf("instance %d: FindAmbiguousLockedModuleEntries = %v, model ambiguousIds = %v\n%+v", i, gotAmbiguous, wantAmbiguous, lock)
		}

		for _, idAtom := range inst.Atoms("Id") {
			id := lockGoldenModuleID(idAtom)
			evaluation := EvaluateVendoredModuleHash(lock, &Module{Metadata: &Invowkmod{Module: id}, Path: moduleDir})
			set, known := statusSet[evaluation.Status]
			if !known || !slices.Contains(inst.Targets(set, lockAtom), idAtom) {
				t.Fatalf("instance %d id %s: EvaluateVendoredModuleHash status %s is not the model's evaluation\n%+v", i, id, evaluation.Status, lock)
			}
		}
	}
}
