name: Bug Report
description: Report a bug in invowk.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

        **Not a bug?** Use [GitHub Discussions](https://github.com/invowk/invowk/discussions) for feature requests, questions, and general help.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      render: shell
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      placeholder: "e.g., 1.26.0"
    validations:
      required: true

  - type: input
    id: invowk-version
    attributes:
      label: Invowk Version
      placeholder: "Run 'invowk version' and paste the output"
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      options:
        - native
        - virtual
        - container
        - N/A
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, logs, or screenshots about the problem.
    validations:
      required: false

  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/invowk/invowk/blob/main/CODE_OF_CONDUCT.md).
          required: true
