// SPDX-License-Identifier: MPL-2.0

package cueutil

import (
	"errors"
	"fmt"
	"strings"
)

// ErrInvalidCUEPath is the sentinel error wrapped by InvalidCUEPathError.
var ErrInvalidCUEPath = errors.New("invalid CUE path")

type (
	// CUEPath represents a JSON/CUE path to a value within a CUE schema
	// (e.g., "cmds[0].name", "env.vars"). A valid CUE path must be non-empty
	// and not whitespace-only. CUE paths are generated by the CUE library
	// during validation error extraction — they are always structurally valid
	// when produced by the library.
	CUEPath string

	// InvalidCUEPathError is returned when a CUEPath value is empty or
	// whitespace-only.
	InvalidCUEPathError struct {
		Value CUEPath
	}
)

// String returns the string representation of the CUEPath.
func (p CUEPath) String() string { return string(p) }

// Validate returns nil if the CUEPath is valid (non-empty, non-whitespace),
// or an error if it is not.
func (p CUEPath) Validate() error {
	if strings.TrimSpace(string(p)) == "" {
		return &InvalidCUEPathError{Value: p}
	}
	return nil
}

// Error implements the error interface for InvalidCUEPathError.
func (e *InvalidCUEPathError) Error() string {
	return fmt.Sprintf("invalid CUE path %q: must be non-empty", e.Value)
}

// Unwrap returns ErrInvalidCUEPath for errors.Is() compatibility.
func (e *InvalidCUEPathError) Unwrap() error { return ErrInvalidCUEPath }
