// SPDX-License-Identifier: MPL-2.0

package audit

const (
	codeModuleMetadataGlobalNoHash           FindingCode = "module-metadata-trust-global-module-has-no-content-hash-verification"
	codeModuleMetadataInvowkfileParseFailure FindingCode = "module-metadata-trust-module-invowkfile-failed-to-parse"
	codeModuleMetadataWideFanOut             FindingCode = "module-metadata-trust-wide-dependency-fan-out"
	codeModuleMetadataSimilarID              FindingCode = "module-metadata-trust-module-id-similar-to-another-module"
	codeModuleMetadataUnpinnedDependency     FindingCode = "module-metadata-trust-module-dependency-has-no-version-constraint"
	codeModuleMetadataTransitiveNotDeclared  FindingCode = "module-metadata-trust-transitive-dependency-not-declared-in-root-invowkmod-cue"
	codeModuleMetadataVendoredNotDeclared    FindingCode = "module-metadata-trust-vendored-module-not-declared-in-requires"
	codeLockfilePresentUnparseable           FindingCode = "lockfile-integrity-lock-file-present-but-unparseable"
	codeLockfileDependenciesNoLock           FindingCode = "lockfile-integrity-module-has-dependencies-but-no-lock-file"
	codeLockfileVendoredNoLock               FindingCode = "lockfile-integrity-vendored-modules-present-without-lock-file"
	codeLockfileSizeUnknown                  FindingCode = "lockfile-integrity-lock-file-size-could-not-be-verified"
	codeLockfileSizeLimit                    FindingCode = "lockfile-integrity-lock-file-exceeds-size-limit"
	codeLockfileUnknownVersion               FindingCode = "lockfile-integrity-unknown-lock-file-version"
	codeLockfileV1NoHashes                   FindingCode = "lockfile-integrity-lock-file-uses-v1-0-format-without-content-hashes"
	codeLockfileV1VendoredNoHashes           FindingCode = "lockfile-integrity-vendored-modules-cannot-be-verified-v1-lock-file-has-no-content-hashes"
	codeLockfileAmbiguousModule              FindingCode = "lockfile-integrity-ambiguous-lock-file-entries-for-same-module"
	codeLockfileVendoredMissingEntry         FindingCode = "lockfile-integrity-vendored-module-has-no-lock-file-entry"
	codeLockfileVendoredHashUnavailable      FindingCode = "lockfile-integrity-vendored-module-hash-could-not-be-computed"
	codeLockfileContentHashMismatch          FindingCode = "lockfile-integrity-module-content-hash-mismatch"
	codeLockfileVendoredHashUnknown          FindingCode = "lockfile-integrity-vendored-module-hash-status-is-unknown"
	codeLockfileOrphanEntry                  FindingCode = "lockfile-integrity-orphaned-lock-file-entry"
	codeLockfileAdditionalOrphans            FindingCode = "lockfile-integrity-additional-orphaned-lock-file-entries"
	codeLockfileRequiredMissingEntry         FindingCode = "lockfile-integrity-required-module-has-no-lock-file-entry"
	codeScriptPathOutsideModule              FindingCode = "script-path-traversal-script-references-path-outside-module-boundary"
	codeScriptAbsolutePath                   FindingCode = "script-path-traversal-module-script-uses-absolute-path"
	codeScriptFileLarge                      FindingCode = "script-execution-script-file-unusually-large"
	codeScriptRemoteExecution                FindingCode = "script-execution-script-downloads-and-executes-remote-code"
	codeScriptBase64Decode                   FindingCode = "script-obfuscation-script-contains-base64-decode"
	codeScriptEvalDynamic                    FindingCode = "script-obfuscation-script-uses-eval-with-dynamic-content"
	codeScriptBase64Subshell                 FindingCode = "script-obfuscation-script-uses-base64-in-subshell"
	codeScriptEncodedPipe                    FindingCode = "script-obfuscation-script-pipes-encoded-content-to-base64"
	codeScriptHexEscapes                     FindingCode = "script-obfuscation-script-contains-hex-escape-sequences"
	codeScriptContentPathTraversal           FindingCode = "script-path-traversal-script-content-contains-path-traversal"
	codeEnvInheritAll                        FindingCode = "env-exfiltration-command-inherits-all-host-environment-variables"
	codeEnvInheritDefaultAll                 FindingCode = "env-exfiltration-command-uses-default-env-inheritance-all-host-variables"
	codeEnvSensitiveVar                      FindingCode = "env-exfiltration-script-accesses-sensitive-environment-variable"
	codeEnvGenericSecret                     FindingCode = "env-exfiltration-script-accesses-generic-secret-variable"        // #nosec G101 -- stable finding code, not a credential.
	codeEnvTokenExtraction                   FindingCode = "env-exfiltration-script-may-extract-credential-to-external-sink" // #nosec G101 -- stable finding code, not a credential.
	codeNetworkReverseShell                  FindingCode = "network-execution-reverse-shell-pattern-detected"
	codeNetworkDNSExfiltration               FindingCode = "network-exfiltration-possible-dns-exfiltration-pattern"
	codeNetworkEncodedURL                    FindingCode = "network-exfiltration-script-contains-encoded-url"
	codeNetworkAccessCommand                 FindingCode = "network-exfiltration-script-uses-network-access-command"
	codeSymlinkFound                         FindingCode = "symlink-path-traversal-symlink-found-in-module-directory"
	codeSymlinkTargetUnreadable              FindingCode = "symlink-path-traversal-symlink-target-could-not-be-read-boundary-check-bypassed"
	codeSymlinkEscapesRoot                   FindingCode = "symlink-path-traversal-symlink-points-outside-module-boundary"
	codeSymlinkDangling                      FindingCode = "symlink-path-traversal-dangling-symlink-in-module-directory"
	codeSymlinkChain                         FindingCode = "symlink-path-traversal-symlink-chain-detected"
	codeSymlinkWalkIncomplete                FindingCode = "symlink-path-traversal-module-directory-walk-incomplete"
	codeCorrelatorCredentialExfiltration     FindingCode = "correlator-credential-exfiltration" // #nosec G101 -- stable finding code, not a credential.
	codeCorrelatorPathSymlinkEscape          FindingCode = "correlator-path-symlink-escape"
	codeCorrelatorObfuscatedExfiltration     FindingCode = "correlator-obfuscated-exfiltration"
	codeCorrelatorTrustChainWeakness         FindingCode = "correlator-trust-chain-weakness"
	codeCorrelatorInterpreterTraversal       FindingCode = "correlator-interpreter-traversal"
	codeCorrelatorMultipleCategories         FindingCode = "correlator-multiple-categories"
	codeCorrelatorHighPlusOther              FindingCode = "correlator-high-plus-other"
	codeCorrelatorMediumPlusMedium           FindingCode = "correlator-medium-plus-medium"
)
